package boundary;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import control.ManagerController;
import entity.ConstantsAndGlobalVars;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.image.ImageView;
import javafx.stage.Modality;
import javafx.stage.Stage;
/**
 * {@inheritDoc}
 * This is the GUI controller responsible for controlling the manager page GUI. It opens different windows for different functionalities the manager can do.
 * It inherits all functionalities form {@link boundary.LibrarianPageController}.
 */
public class ManagerPageController extends LibrarianPageController{
	/**
	 * instance variables:
	 * managerController - an instance of ManagerController used to send various requests to the server.
	 */
	private ManagerController managerController;

	@FXML
	private Button cardOperationBtn;

	@FXML
	private Button viewDataBtn;

	/**
	 * opens the windows responsible for all card operations.
	 * @param event - auto-generated by SceneBuilder.
	 * @throws IOException - thrown should loading the FXML file encounter a problem.
	 */
    @FXML
    void cardOperationHandler(ActionEvent event) throws IOException {
    	Stage primaryStage = new Stage();
		primaryStage.setAlwaysOnTop(true);
		primaryStage.initModality(Modality.APPLICATION_MODAL);
		FXMLLoader loader = new FXMLLoader();
		Parent root = loader.load(getClass().getResource("/boundary/CardOperationGUI.fxml").openStream());
		primaryStage.setScene(new Scene(root));
		primaryStage.setTitle("Card operation");
		primaryStage.show();
    }


	/**
	 * opens the windows responsible for viewing all data.
	 * @param event - auto-generated by SceneBuilder.
	 * @throws IOException - thrown should loading the FXML file encounter a problem.
	 */
    @FXML
    void viewDataHandler(ActionEvent event) throws IOException {
    	Stage primaryStage = new Stage();
		primaryStage.setAlwaysOnTop(true);
		primaryStage.initModality(Modality.APPLICATION_MODAL);
		FXMLLoader loader = new FXMLLoader();
		Parent root = loader.load(getClass().getResource("/boundary/DataAndReportsGUI.fxml").openStream());
		primaryStage.setScene(new Scene(root));
		primaryStage.setTitle("Data & Reports");
		primaryStage.show();
    }

	/**
	 * called upon loading the FXML file, initialises some GUI elements and instance variables.
	 */
    @FXML
    void initialize() {
    	super.initialize();
    	managerController = ManagerController.getInstance(ConstantsAndGlobalVars.ipAddress, ConstantsAndGlobalVars.DEFAULT_PORT);

    	String img = "/pictures/card.png";
    	cardOperationBtn.setStyle("-fx-background-image: url('"+img+"'); "+"-fx-min-height: 132px; "+"-fx-min-width: 128px;" + "-fx-background-size: 100px 100px;"+"-fx-background-repeat: no-repeat;"+"-fx-background-position: center 8px;"+"-fx-border-color: #0090ff;"+"-fx-border-radious: 5;"+"-fx-border-width: 2;");
		img = "/pictures/viewData.png";
		viewDataBtn.setStyle("-fx-background-image: url('"+img+"'); "+"-fx-min-height: 132px; "+"-fx-min-width: 128px;" + "-fx-background-size: 100px 100px;"+"-fx-background-repeat: no-repeat;"+"-fx-background-position: center 8px;"+"-fx-border-color: #0090ff;"+"-fx-border-radious: 5;"+"-fx-border-width: 2;");
		
    }
}
